# Numpy 기초연습문제

#### 201821479 황혜린
---

In [1]:
import numpy as np

## 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [2]:
a = np.zeros((3, 4))  # 행:3, 열:4
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.


    array([[ 1.,  2.,  3.,  4.],        
           [ 5.,  6.,  7.,  8.],     
           [ 9., 10., 11., 12.]])     

In [3]:
for i in range(a.shape[0]):  #i는 행
    for j in range(a.shape[1]):  # j는 열
        a[i, j] = i*4 + j + 1  # 행렬값 생성 (ex. a[0,0]=0*4+0+1)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [4]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num     
        num += 1   # num에 1을 더한다(반복)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [5]:
a[1, 2]  # 두번째 열 3번째 행

7.0

## 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.

`array([[5., 6., 7., 8.]])`

In [21]:
a.shape  # 행렬의 차원 출력

(3, 4)

In [7]:
a[[1], :]  # 두번째 행의 모든 열 출력

array([[5., 6., 7., 8.]])

## 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

    array([[ 2.,  3.],
           [ 6.,  7.],
           [10., 11.]])  

In [22]:
a[:,[1, 2]]  #a의 둘째열, 셋째열

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.]])

## 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리안 인덱싱을 하시오.
`array([1., 2., 3., 4., 5., 6.])`

In [11]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result  # np.asarray를 사용하여 6이하의 값을 갖는 array생성

array([1., 2., 3., 4., 5., 6.])

In [12]:
a[a <= 6] # a에서 6이하의 값 출력

array([1., 2., 3., 4., 5., 6.])

## 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [23]:
b = np.random.random((3, 4))  # 행렬의 크기는 3*4, 행렬의 모든 요소는 1이하
b

array([[0.67884093, 0.5656555 , 0.29995961, 0.18357454],
       [0.66633511, 0.77684607, 0.13501626, 0.96981229],
       [0.31292993, 0.34188341, 0.53231299, 0.45684947]])

## 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [14]:
c = a * b  #a와 b의 요소곱
c

array([[0.83978611, 0.72428638, 1.35021053, 0.73643004],
       [1.9366791 , 0.11952979, 5.8595986 , 1.51365693],
       [3.88756413, 3.85522083, 0.60386897, 4.77004599]])

## 9. b의 전치행렬을 구하여 d에 저장하시오.

In [16]:
d = b.T  # b의 전치행렬
d  

array([[0.83978611, 0.38733582, 0.43195157],
       [0.36214319, 0.01992163, 0.38552208],
       [0.45007018, 0.83708551, 0.05489718],
       [0.18410751, 0.18920712, 0.39750383]])

In [17]:
d.shape # 행렬의 차원 출력

(4, 3)

## 10. a와 d에 대하여 각 차원의 크기를 출력하시오.


In [18]:
print(a.shape, d.shape)  # a,d 각각의 차원을 출력

(3, 4) (4, 3)


## 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [19]:
e = a.dot(d)  # a와 d의 행렬곱
e

array([[ 3.65071306,  3.69526409,  2.9577026 ],
       [10.99514101,  9.42946441,  8.03720126],
       [18.33956896, 15.16366474, 13.11669992]])

## 12. e에 대하여 각 열의 합을 계산하시오.

In [20]:
np.sum(e, axis=1)  # axis=1, 즉 y축을 기준으로 합을 구한다

array([10.30367975, 28.46180668, 46.61993362])